keys:
  - &nix-builder age17n6fg2w2gfs4tqwgac9vw4xzs6xlkpdzfa0c9wqvfkz3utqxrg2sssewe8
creation_rules:
  - path_regex: secrets/(notes\.md|caddy_public_private|nix_builder|nix_main|rusherhack_plugin_compiler|atticd.env.bin)$
    key_groups:
      - age:
          - *nix-builder
